[package]
name = "automator"
version = "0.1.0"
authors = ["Logan Saso <logansaso@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reqwest = "0.9.20"
# discord = { branch = "master", git = "https://github.com/SpaceManiac/discord-rs" }
regex = "1.3.1"
lazy_static = "1.4.0"
itertools = "0.8.0"
